name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run ./manage.py test
      - run: pipenv run flake8 .

  load_test:
    runs-on: ubuntu-latest
    needs: test_project
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - run: pip install locust
      - name: Run Locust load test
        run: |
          locust -f locustfile.py --headless -u 100 -r 10 --run-time 1m --host http://localhost:8000
